### ISSUE TITLE
Fallback font search is to strict

### ISSUE THREAD

**Issue by snaggen** [pop-os/cosmic-term#104]
When looking in to #66, it turns out that it was just a matter of the Braille font I had installed, not having my selected default weight. And since this is just a minor corner case with an easy fix by installing Iosevka font, I thought that is a behaviour that is ok. After all, it is the "Correct" behavior. 

However, I just ran in to another usecase where this is a more severe issue. I do some programing related to subtitles, hence I work with some different languages. They are not that important to me since I do not understand them, but I still need to make sure that they are displayed and handled correct. Now it turns out I cannot look at Arabic and Chinese text in cosmic-term with my default terminal settings.

I normally have my default font as JetBrains Mono, but with Light or Extra Light weight as default. Using that, I looked some unit tests related to text in arabic, and realize that in cosmic-term I cannot se the text
```
 "الذي يثير الكثير من المشاكل الاجتماعية ،",
```
If I switch to Normal font weight it will be displayed. 
The same with the chinese text
```
"嘿，Lena! 怎么样，你好吗？
```

Looking at it in wezterm and alacritty, it seems they will fallback to fonts with the wrong weight if no exact match is found. This is a behaviour I think is better, since that will actually show something instead of weird "glyph is missing" symbols. The text is of course looks a bit out of place, but you can actually read it and if it is important that it looks good to you it is still fixable by installing a better font.

So, to reproduce you can try the following:
1. Set the default font to JetbransMono
2. Set ExtraLight as the default weight
3. Write the text above to a text file and try to view that in Cosmi Term.

**Comment by MoSal** [comment]
This is a `cosmic-text` issue. It's all in [this file](https://github.com/pop-os/cosmic-text/blob/main/src/font/fallback/mod.rs) and [this file](https://github.com/pop-os/cosmic-text/blob/main/src/font/system.rs) (`get_font_matches` in particular) if you want to have a crack at it.

This is the relevant calling code in `src/shape.rs`:

``` rust
    let attrs = attrs_list.get_span(start_run);
    let fonts = font_system.get_font_matches(attrs);
    let default_families = [&attrs.family];
    let mut font_iter = FontFallbackIter::new(
        font_system,
        &fonts,
        &default_families,
        &scripts,
        &line[start_run..end_run],
    );
```

One approach that can still be confined to monospace fallback is to use "the closest font weight, lower first" instead of "the closest font weight equal or less".

So basically replacing the `checked_sub()` here with `abs_diff()`:

https://github.com/pop-os/cosmic-text/blob/e0ae465f918cd1cffca3a8239547dcf8166d3f77/src/font/system.rs#L154

Removing the `<=` condition here:

https://github.com/pop-os/cosmic-text/blob/e0ae465f918cd1cffca3a8239547dcf8166d3f77/src/attrs.rs#L176-L183


And adding a `weight` field above `id` here:

https://github.com/pop-os/cosmic-text/blob/main/src/font/fallback/mod.rs#L39-L43

---

Installing Cascadia Mono fonts (maybe Kawkab Mono too) could also be of help as a workaround, at least with Arabic.

---

> but you can actually read it

No, not really. You can *decipher* it maybe, but not really read it. Definitely not in Arabic's case. Most definitely not in Alacritty. And in Wezterm's case, Bidi/RTL support is below basic, and what's supposedly supported still has (known) issues. But at least there is/was an attempt.

There is a reason why `cosmic-term` got me interested after all ;) The basics are already there. And with a couple of features and fixes I'm testing out, RTL support will be complete, at least as far as I'm concerned.

**Comment by MoSal** [comment]
> One approach that can still be confined to monospace fallback is to use "the closest font weight, lower first" instead of "the closest font weight equal or less".

PR incoming.

**Comment by i0rxg** [comment]
how to get a better arabic font displayed alongside JetBrainsMono?
