### ISSUE TITLE
Making invalid profile bricks Terminal forever

### ISSUE THREAD

**Issue by silverhadch** [pop-os/cosmic-term#274]
I made an invalid Profile and set it as Standad and when i wanted to change it i can no longer launch the Terminal it is simply broken.

**Comment by RossBarnie** [comment]
Assuming you're on Linux, try changing the contents of `$HOME/.config/cosmic/com.system76.CosmicTerm/v1/default_profile` to `None`.

**Comment by silverhadch** [comment]
> Assuming you're on Linux, try changing the contents of `$HOME/.config/cosmic/com.system76.CosmicTerm/v1/default_profile` to `None`.

Thanks but why assume on Linux i dont quite remeber Windows or Mac supporting other then their own DE.

**Comment by RossBarnie** [comment]
Because throughout the codebase there are compiler flags for redox, windows and Mac, each of which have different destinations for these config files.

-------- Original Message --------

**Comment by joshuamegnauth54** [comment]
I love the title of this issue.

The problem is that the program closes new tabs if it fails to launch a terminal. Creating a new tab with an invalid profile would lead to that tab's destruction. This is fine if multiple tabs are open, but if COSMIC Term is launched with an invalid default profile the _only_ open tab is closed and thus the program closes.

Pretty amusing! Anyway, I'm opening a PR that fixes it.
