### ISSUE TITLE
"Select all" captures empty lines

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-term#92]
CTRL+Shift+A will copy lines under the last prompt. Should only capture the last prompt and above.

**Comment by MoSal** [comment]
The pedant in me is asking:

* What if the white-space is significant?
* Could this behavior give the wrong impression about what terminal emulators actually know/how they are implemented?

**Comment by jackpot51** [comment]
I'm not sure I understand the questions @MoSal. All this change does is drop trailing empty lines from the selection when doing select all, by definition there is no information in those lines. If you want to select them it can still be done manually.

**Comment by MoSal** [comment]
Let me mention again that I'm being pedantic here.

>  trailing empty lines

But are they really empty...

``` zsh
local lines=`tput lines`
local cols=`tput cols`
for _ in {1..$((lines-3))}; do
  for _ in {1..$cols}; do
    echo -n ' '
  done; echo
done
```

Lines will  be skipped here (untested). If we remove the `; echo` part, the lines will not be skipped (untested) because of `WRAPLINE` being set on the last cell of each row. The output in both cases looks exactly the same. And in both cases, my pedantic self would argue that the lines are not really *empty*.

So what I'm pedantically arguing here is that implementing this feature may give users the wrong idea about what the terminal actually knows or doesn't know.

Note that, unless I missed it, `alacritty_terminal` cells don't have an erased (initial) state. There is no distinction between initially empty/unused cells, and cells with *real* spaces. This is fine since the distinction is not that useful, and possibly misleading, as spaces would be used later to denote emptiness anyway, even in implementations that do have the distinction.

**Comment by jackpot51** [comment]
Could you present a case where trimming trailing lines that consist only of spaces could cause issues?

**Comment by MoSal** [comment]
Same previous examples, bit ending with `| cat`.

Imagine them being a part of a bizarre application that asks you to copy printed text and pass it to a hash function, then hitting `Ctrl-c`.

Maybe trimming starting at cursor would provide more consistent/expected behavior, with the space under cursor only trimmed if `!grid.cursor.input_needs_wrap`.

**Comment by jackpot51** [comment]
> Imagine them being a part of a bizarre application that asks you to copy printed text and pass it to a hash function, then hitting Ctrl-c.

This would have issues with select all selecting the entire grid too, as it could select beyond any outputted spaces. I could use the cursor position to determine how far to trim, but I'm not particularly seeing a need to do this as the terminal program would have to hang waiting for input with the cursor on an otherwise empty line for this to be any different from the current logic, so I'll just be leaving it how it is.
